name: "Fabric CLI Action"
description: "GitHub Action to run Fabric CLI commands for Microsoft Fabric resources."
inputs:
  resource_type:
    description: "The type of Fabric resource (e.g., workspaces)"
    required: true
  action:
    description: "Action to perform (e.g., create, list)"
    required: true
  value:
    description: "The value being passed to the action (e.g., workspace name)"
    required: false

runs:
  using: "docker"
  image: "ghcr.io/stevenbuglione/fabric-cli:release"
  env:
    AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}  # Assume these are passed from the workflow
    AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
    AZURE_CLIENT_SECRET: ${{ env.AZURE_CLIENT_SECRET }}
  args:
    - ${{ inputs.resource_type }}
    - ${{ inputs.action }}
    - ${{ inputs.value || '' }}