name: "Fabric Resource Management"

on:
  workflow_call:
    inputs:
      resource_type:
        required: true
        type: string
      action:
        required: true
        type: string
      value:
        required: false
        type: string
    secrets:
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  run-fabric-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Fabric CLI Command
        uses: ./.github/actions/fabric-cli-action
        with:
          resource_type: ${{ inputs.resource_type }}
          action: ${{ inputs.action }}
          value: ${{ inputs.value }}
        env:  # Pass secrets as environment variables
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}